mixed-port: 7890

# 授权账号密码
# authentication:
#   - "user:pwd"

allow-lan: true
mode: rule
log-level: warning
external-controller: 0.0.0.0:9090
external-ui: ui
secret: "pwd"

dns:
  enabled: true
  listen: 0.0.0.0:53
  ipv6: true
  prefer-h3: true
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - "+.lan"
    - "+.local"
  default-nameserver:
    - 223.5.5.5
    - 119.29.29.29
    - 1.1.1.1
    - 8.8.8.8
  nameserver:
    - https://1.1.1.1/dns-query
    - https://8.8.8.8/dns-query
    - tls://one.one.one.one:853
    - tls://dns.google:853
    - https://one.one.one.one/dns-query
    - https://dns.google/dns-query
  nameserver-policy:
    geosite:cn,private:
      - https://223.5.5.5/dns-query
      - https://119.29.29.29/dns-query
      - tls://doh.pub:853
      - tls://dns.alidns.com:853
      - https://doh.pub/dns-query
      - https://dns.alidns.com/dns-query

proxy-groups:
  - {
      name: ♻️ 自动选择,
      type: url-test,
      use: [proxies],
      url: "http://www.gstatic.com/generate_204",
      interval: 3600,
    }

proxy-providers:
  proxies:
    type: http
    url: URL # 这里添加clash订阅链接
    interval: 86400
    path: ./proxies.yaml

rules:
  - DOMAIN-KEYWORD,wogg,DIRECT
  - MATCH,♻️ 自动选择